import os
import base64
import json
from datetime import datetime


def get_document_types():
    """Return a list of common document types for Simplifile"""
    return [
        "Deed",
        "Deed - Timeshare",
        "Mortgage",
        "Assignment of Mortgage",
        "Satisfaction of Mortgage",
        "Mortgage Satisfaction",
        "Deed of Trust",
        "Release of Lien",
        "Affidavit",
        "Amendment",
        "Lien",
        "Modification",
        "Power of Attorney",
        "UCC Financing Statement"
    ]

def get_instrument_types():
    """Return a list of instrument types from Simplifile API spec"""
    return [
        "Affidavit",
        "Affidavit - Lien Book",
        "Agreement Deed Book",
        "Agreement Mortgage Book",
        "Amed of Partnership",
        "Amendment Deed Book",
        "Articles of Association",
        "Articles of Incorporation",
        "Assignment Deed",
        "Assignment Mortgage",
        "Assignment of Lease",
        "Assignment of Lease Rents and Profits - Deed Book",
        "Bankruptcy",
        "Bill of Sale",
        "Blanket Partial Release - Deed Book",
        "Blanket Partial Release - Mortgage Book",
        "Certificate of Death",
        "Child Support Lien",
        "Child Support Lien Satisfaction",
        "Condemnation",
        "Condo Lien",
        "Condo Lien - Amendment",
        "Condo Lien - Partial Release",
        "Condo Lien Satisfaction",
        "Condo Plat",
        "Contract of Sale",
        "Contractors Notice of Project",
        "Court Order Deed",
        "Deed",
        "Deed - Timeshare",
        "Dissolution of Partnership",
        "Easement",
        "Federal Tax Partial Release",
        "Federal Tax Satisfaction",
        "Federal Tax Withdrawal",
        "HCG Deed",
        "HCG Easement",
        "HCG Plat - Non-Legal Size",
        "Lease",
        "Lease Agreement",
        "Lien Satisfaction Rescission",
        "Lis Pendens Deed",
        "Lis Pendens Deed Release",
        "Lis Pendens Deed Satisfaction",
        "Lis Pendens Mortgage",
        "Lis Pendens Mortgage Release",
        "Lis Pendens Mortgage Satisfaction",
        "Manufactured Home Lien Affidavit",
        "Manufactured Home Satisfaction Affidavit",
        "Manufactured Home Severance Affidavit",
        "Manufactured Home Title Retirement",
        "Master Deed",
        "Mechanics Lien",
        "Mechanics Lien - Partial Release",
        "Mechanics Lien - Sep. Aff. Of Server",
        "Mechanics Lien Amendment",
        "Mechanics Lien Satisfaction",
        "Mechanics Lien Surety Bond",
        "Memorandum of Trust",
        "Mental Health Amendment",
        "Mental Health Lien",
        "Mental Health Lien Satisfaction",
        "Merger",
        "Meter Conservation Notice",
        "Meter Conservation Satisfaction",
        "Military Discharge",
        "Misc - Deeds With Pages",
        "Misc - Lien",
        "Misc - Lien Satisfaction",
        "Misc - Mortgage With Pages",
        "Misc Mortgage Book",
        "Mortgage",
        "Mortgage Book - No Charge",
        "Mortgage Modification",
        "Mortgage Partial Release",
        "Mortgage Satisfaction",
        "Mortgage Satisfaction Rescission",
        "Notice of Bankruptcy Discharge",
        "Notice of Foreclosure",
        "Notice of Pledge of Real Estate",
        "Notice of Termination",
        "Option",
        "Ordinance",
        "Partnership Agreement",
        "Plat - Legal Size",
        "Plat - Other Than Legal Size",
        "Plat Book - No Charge",
        "Power of Attorney",
        "Power of Attorney Revocation",
        "Probate Fiduciary Letter (Charge)",
        "Probate Fiduciary Letter Revocation",
        "Release - Deed Book",
        "Restrictions",
        "Revocation of Release",
        "Satisfaction - Deed Book",
        "State Tax Partial Release",
        "State Tax Withdrawal",
        "Sublease",
        "Subordination Agreement - Deed Book",
        "Subordination Agreement - Mortgage Book",
        "Subordination Agreement - Plat Book",
        "Tax Lien Amendment",
        "Tax Lien Expungement",
        "Tax Liens - Federal Charge",
        "Tax Liens - State",
        "Tax Satisfaction",
        "Trust Agreement",
        "Trust Agreement Revocation",
        "UCC1",
        "UCC3",
        "UCC3 Assignment",
        "UCC3 Termination",
        "Waiver"
    ]

def get_helper_document_types():
    """Return a list of helper document types for Simplifile"""
    return [
        "PT-61",
        "Tax Form",
        "Cover Sheet",
        "Other"
    ]

def format_date(date_obj):
    """Format a date object for Simplifile API"""
    if isinstance(date_obj, datetime):
        return date_obj.strftime("%m/%d/%Y")
    return date_obj